name: Magic Circle Auto Sync

# This workflow is for projects using Magic Circle framework
# It will only run if .mc/scripts/ exist in the repository

on:
  issues:
    types: [closed, reopened]
  push:
    branches: [main]
    paths-ignore:
      - '.github/workflows/magic-circle-sync.yml'  # Avoid recursive triggers
  workflow_dispatch:

jobs:
  sync-project-state:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh
    
    - name: Authenticate GitHub CLI
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
    
    - name: Check for required scripts
      id: check-scripts
      run: |
        if [ -f ".mc/scripts/update_project_state.py" ]; then
          echo "scripts_exist=true" >> $GITHUB_OUTPUT
        else
          echo "scripts_exist=false" >> $GITHUB_OUTPUT
          echo "⚠️ Magic Circle sync scripts not found in this repository"
          echo "This workflow is designed for projects using Magic Circle framework"
        fi
    
    - name: Check for closed issues and update state
      if: steps.check-scripts.outputs.scripts_exist == 'true' && github.event_name == 'issues' && github.event.action == 'closed'
      run: |
        echo "🎯 Issue #${{ github.event.issue.number }} was closed"
        python3 .mc/scripts/update_project_state.py
    
    - name: Regular sync on push
      if: steps.check-scripts.outputs.scripts_exist == 'true' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
      run: |
        echo "📊 Running regular project state sync"
        python3 .mc/scripts/check_closed_issues.py 24
    
    - name: Commit and push changes
      if: steps.check-scripts.outputs.scripts_exist == 'true' && success()
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore: auto-sync project state [skip ci]"
          git push